== JBoss Fuse Forge Addon
:idprefix: id_ 
The JBoss Fuse addon adds the following capabilities to JBoss Forge:

* Creation of new Jboss Fuse projects
* Camel component development kit

=== Depends on

[options="header"]
|===
|Addon |Exported |Optional

|cdi
|no
|no

|maven
|no
|no

|parser-java
|no
|no

|parser-xml
|no
|no

|projects
|no
|no

|shell
|no
|no

|templates
|no
|no

|ui
|no
|no

|===

== Setup

This Addon requires the following installation steps.

=== Add configuration to pom.xml 

To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.jboss.fuse.forge.addon</groupId>
   <artifactId>fuse-forge</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----

== Features

==== Create a new JBoss Fuse project

To create a new JBoss Fuse, use the following command:

[source]
----
project-new --named my-fuse-project --type fuse
----


==== Camel Component Development Kit

To setup an existing project for use with the Camel Component Development kit:

[source]
----
api-component-setup
----

The following commands will then become available for you to add & configure APIs:

[source]
----
api-component-add-alias
api-component-add-extra-option
api-component-exclude-config-names
api-component-exclude-javadoc-methods
api-component-add-api
api-component-add-nullable-option
api-component-exclude-config-types
api-component-exclude-javadoc-packages
api-component-add-config-to-generate-from-javadoc
api-component-add-substitution
api-component-exclude-javadoc-classes
api-component-include-javadoc-static-methods
----